/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package q2;

import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.*;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author priyu
 */
public class WordSearchWindow extends javax.swing.JFrame {

    /**
     * Creates new form WordSearchWindow
     */
    public WordSearchWindow() {
        initComponents();
    }
    
    Connection con=null;
    Statement stmt=null;
    ResultSet rs=null,rs1=null;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        srch = new javax.swing.JTextField();
        btnsrch = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        wrdmng = new javax.swing.JTextField();
        wrdsyn = new javax.swing.JTextField();
        wrdant = new javax.swing.JTextField();
        insrettxt = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Word Search Window");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 250, 60));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("Enter Word");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 140, 40));

        srch.setText("Enter word here");
        getContentPane().add(srch, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 159, 190, 40));

        btnsrch.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnsrch.setText("Search");
        btnsrch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsrchActionPerformed(evt);
            }
        });
        getContentPane().add(btnsrch, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 450, 180, 40));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setText("Word Meaning");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setText("Synonym");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 120, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setText("Antonym");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 110, -1));
        getContentPane().add(wrdmng, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 190, 40));
        getContentPane().add(wrdsyn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 190, 40));
        getContentPane().add(wrdant, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 190, 40));

        insrettxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        insrettxt.setText("Insert");
        insrettxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insrettxtActionPerformed(evt);
            }
        });
        getContentPane().add(insrettxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 365, 180, 40));

        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(666, 280, 170, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insrettxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insrettxtActionPerformed
        
        if(srch.getText().isEmpty()|| wrdmng.getText().isEmpty() || wrdsyn.getText().isEmpty() || wrdant.getText().isEmpty())
      {
          JOptionPane.showMessageDialog(this,"Missing Information");
          return;
      }
        
        try{
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/wordsearch?zeroDateTimeBehavior=CONVERT_TO_NULL","root","root");
            PreparedStatement ps =con.prepareStatement("insert into wordsrch values(?,?,?,?)");
            ps.setString(1, srch.getText());
            ps.setString(2,wrdmng.getText());
            ps.setString(3, wrdsyn.getText());
            ps.setString(4, wrdant.getText());
            ps.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Word Inserted into database");
            con.close();
        }
        catch(HeadlessException | ClassNotFoundException | SQLException e){
            System.out.println(e);
        } 
        
        srch.setText(" ");
        wrdmng.setText(" ");
        wrdsyn.setText(" ");
        wrdant.setText(" ");
        
        
    }//GEN-LAST:event_insrettxtActionPerformed

    private void btnsrchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsrchActionPerformed
       
        if(srch.getText().isEmpty())
      {
          JOptionPane.showMessageDialog(this,"Missing Information");
          return;
      }
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/wordsearch","root","root");
            stmt = con.createStatement();
            
            
            rs = stmt.executeQuery("select meaning,synonym,antonym from wordsrch where word='"+srch.getText()+"'");
            
            rs.next();
         
                wrdmng.setText(rs.getString(1));
                wrdsyn.setText(rs.getString(2));
                wrdant.setText(rs.getString(3));
                
                con.close();
    
        }
        catch(ClassNotFoundException | SQLException e)
        {
            System.out.println(e);
        }
        wrdmng.disable();
        wrdsyn.disable();
        wrdant.disable();
        
    }//GEN-LAST:event_btnsrchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        wrdmng.setText(" ");
        wrdsyn.setText(" ");
        wrdant.setText(" ");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WordSearchWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WordSearchWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WordSearchWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WordSearchWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WordSearchWindow().setVisible(true);
            }
        });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsrch;
    private javax.swing.JButton insrettxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField srch;
    private javax.swing.JTextField wrdant;
    private javax.swing.JTextField wrdmng;
    private javax.swing.JTextField wrdsyn;
    // End of variables declaration//GEN-END:variables

}